classifier/urls.py
from django.urls import path

from classifier import views

app_name = "classifier"

urlpatterns = [
    path("", views.ClassifyView.as_view(), name="classify"),
    path("load-subs/", views.LoadSubsView.as_view(), name="load-subs"),
    path("upload/", views.SourceUploadView.as_view(), name="upload-files"),
]

columnclasses/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("classifier.urls", namespace="classify-home")),
    path("classify/", include("classifier.urls", namespace="classify")),
]

urlpatterns += staticfiles_urlpatterns()

classifier/models.py
from typing import Tuple

from django.db import models

from columnclasses.models import TimeStampedModel


class Source(TimeStampedModel):
    """The CSV linking model from the file to Columns"""

    # The actual file
    document = models.FileField(upload_to="uploads")

    # time that we classified the Columns for this Source
    time_classified = models.DateTimeField(blank=True, null=True)

    def __str__(self) -> str:
        return self.document.name


class Classification(TimeStampedModel):
    """A type that a Column can be"""

    # what we are labeling the column - a target for a classifier
    label = models.CharField(max_length=255)

    # human words on what this is
    description = models.TextField(blank=True)

    # A Classification can be either a main classification or a sub-classification.
    main = models.BooleanField(default=False)

    # Main classifications will add sub-Classifications here.
    subclasses = models.ManyToManyField("self", blank=True)

    class Meta:
        ordering = ("id",)

    def __str__(self) -> str:
        return self.label


class Column(TimeStampedModel):
    """a column in a CSV"""

    # The CSV-storing model
    source = models.ForeignKey("Source", on_delete=models.CASCADE)

    # position of the column, left to right
    index = models.IntegerField()

    # The top level classification (address, name, etc)
    main_class = models.ForeignKey(
        "Classification", on_delete=models.SET_NULL, null=True
    )

    # The sub classification (mailing, property, full, first, etc)
    sub_class = models.ForeignKey(
        "Classification",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="columns",
    )

    # Descriptive stats as a JSON object (sqlite doesn't have JSONField)
    # analysis = JSONField(blank=True)
    analysis = models.TextField(blank=True)

    @staticmethod
    def get_lbl(c: Classification) -> str:
        if c is not None:
            return c.label
        return ""

    @property
    def labels(self) -> Tuple[str, str]:
        return self.get_lbl(self.main_class), self.get_lbl(self.sub_class)

    def __str__(self) -> str:
        return f"{self.source.document.name[:10]} - Column {self.index}"

columnclasses/models.py
from django.db import models


class TimeStampedModel(models.Model):
    """a model with timestamps"""
    created = models.DateTimeField(auto_now_add=True)

    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

classifier/forms.py
from django import forms

from classifier.models import Column, Classification, Source


class ColumnClassifierForm(forms.ModelForm):
    index = forms.IntegerField(widget=forms.HiddenInput())

    class Meta:
        model = Column
        fields = ["index", "main_class", "sub_class"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["sub_class"].queryset = Classification.objects.none()


class SourceUploadForm(forms.Form):
    document = forms.FileField(
        widget=forms.ClearableFileInput(attrs={"multiple": True})
    )

classifier/views.py
import csv
import json
import random

from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView
from django.views.generic.edit import FormView

from classifier.forms import SourceUploadForm
from classifier.models import Classification, Source, Column


class ClassifyView(TemplateView):
    """display some CSVs for column classification"""

    template_name = "classifier/classify.html"

    @csrf_exempt
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        src_id = random.choice(
            Source.objects.filter(time_classified=None).values_list("id", flat=True)
        )
        source = Source.objects.get(id=src_id)
        context["source"] = source
        with source.document.open("r") as f:
            reader = csv.reader(f, delimiter=",")
            lines = list(reader)
            context["headers"] = lines.pop(0)
            context["rows"] = lines[:9]
        mains = Classification.objects.filter(main=True).values_list("id", "label")
        context["mains"] = mains
        context["completion"] = f"{Source.objects.filter(time_classified__isnull=False).count()} / {Source.objects.count()}"
        return context

    def get(self, request, *args, **kwargs):
        if Source.objects.filter(time_classified=None).count() > 0:
            return super().get(request, *args, **kwargs)
        else:
            messages.info(request, "Upload some files to get started!")
            return redirect(reverse_lazy("classify-home:upload-files"))

    def post(self, request, *args, **kwargs):
        body = json.loads(request.body.decode("utf-8"))
        source = Source.objects.get(id=body.pop("sourceId"))
        for k, v in body.items():
            main = Classification.objects.get(id=v["main"]) if v.get("main") else None
            sub = Classification.objects.get(id=v["sub"]) if v.get("sub") else None
            Column.objects.create(
                source=source, index=k, main_class=main, sub_class=sub
            )
        messages.success(request, "Classified successfully!")
        source.time_classified = timezone.now()
        source.save()
        return JsonResponse(
            status=200, data={"location": reverse_lazy("classify:classify")}
        )


class LoadSubsView(View):
    """AJAX loader for subclassifications"""

    @csrf_exempt
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        """get the subclassifications for a given main classification"""
        body = json.loads(request.body.decode("utf-8"))
        parent_id = body.get("id")
        subs = (
            Classification.objects.get(id=parent_id)
            .subclasses.all()
            .order_by("label")
            .values_list("id", "label")
        )
        subs = {c[0]: c[1] for c in subs}
        return JsonResponse(data=subs)


class SourceUploadView(FormView):
    form_class = SourceUploadForm
    template_name = "classifier/upload.html"
    success_url = reverse_lazy("classify:classify")

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        files = request.FILES.getlist("document")
        if form.is_valid():
            sources = []
            for f in files:
                sources.append(Source(document=f))
            Source.objects.bulk_create(sources)
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}CSV Column Classifier{% endblock title %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    {% block extracss %}{% endblock extracss %}

</head>

<body>
<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Ivy</a>
    <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
    <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
            <a class="nav-link" href="#">Sign out</a>
        </li>
    </ul>
</nav>

<div class="container-fluid">
    <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
            <div class="sidebar-sticky">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link active" href="/admin">
                            <span data-feather="home"></span>
                            Admin <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'classify:classify' %}">
                            <span data-feather="home"></span>
                            Classify
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'classify:upload-files' %}">
                            <span data-feather="file"></span>
                            Upload
                        </a>
                    </li>
                    {% block extra-main-nav %}{% endblock extra-main-nav %}

                </ul>

                <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                    <span>Recently Classified</span>
                    <a class="d-flex align-items-center text-muted" href="#">
                        <span data-feather="plus-circle"></span>
                    </a>
                </h6>
                <ul class="nav flex-column mb-2">
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            Put recently classified files here
                        </a>
                    </li>
                </ul>
                <hr/>
                {% block extrasidebar %}{% endblock extrasidebar %}
                <ul class="nav flex-column mb-2">
                    {% for message in messages %}
                        <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            {{ message }}
                        </div>
                    {% endfor %}
                </ul>
            </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
                <h1 class="h2">{% block main-title %}Main Div{% endblock main-title %}</h1>
            </div>

            {% block content %}Put your content here{% endblock content %}

        </main>
    </div>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

{% block extrajs %}{% endblock extrajs %}


<!-- Icons -->
<script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
<script>
    feather.replace()
</script>


</body>
</html>

templates/classifier/classify.html
{% extends "base.html" %}
{% load static %}

{% block main-title %}Classify - {{ source.document.name }}{% endblock main-title %}

{% block extracss %}
    <style>
        .btn-group-xs > .btn, .btn-xs {
            padding: .45rem .25rem;
            font-size: .7rem;
            line-height: .6;
            border-radius: .2rem;
        }
    </style>
{% endblock extracss %}

{% block extrasidebar %}
    <button class="btn btn-primary" onClick="sendFormData({{ headers|length }})">Classify CSV</button>
    <p class="text-muted" style="font-size: 0.8em;">Progress: {{ completion }}</p>
{% endblock extrasidebar %}

{% block content %}
    <div class="table-responsive">
        <table class="table table-striped table-sm" style="font-size: 0.7em;">
            <thead>
            <tr>
                {% for th in headers %}
                    <th scope="col">{{ th }}</th>
                {% endfor %}
            </tr>
            </thead>
            <tbody>
            {% for tr in rows %}
                <tr>
                    {% for td in tr %}
                        <td>{{ td }}</td>
                    {% endfor %}
                </tr>
            {% endfor %}
            <tr>
                {% for td in headers %}

                    <td>
                        <div class="btn-group-vertical btn-group-xs btn-group-toggle" data-toggle="buttons">
                            {% for option in mains %}
                                <label class="btn btn-xs btn-outline-primary"
                                       id="main-{{ forloop.parentloop.counter0 }}"
                                       data-value="{{ option.0 }}"
                                       onclick="loadOptions({{ option.0 }}, 'sub-div-{{ forloop.parentloop.counter0 }}', {{ forloop.parentloop.counter0 }})">
                                    <input type="radio"/>
                                    {{ option.1|default:"reject" }}
                                </label>
                            {% endfor %}
                        </div>
                        <hr/>
                        <div class="btn-group-vertical btn-group-xs btn-group-toggle"
                             id="sub-div-{{ forloop.counter0 }}"
                             data-toggle="buttons"></div>
                    </td>

                {% endfor %}
            </tr>
            </tbody>
        </table>
    </div>
{% endblock content %}

{% block extrajs %}
    <script>let sourceId = {{ source.id }};</script>
    <script type="text/javascript" src="{% static 'js/jquery.doublescroll.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/classify.js' %}"></script>
{% endblock extrajs %}

templates/classifier/upload.html
{% extends "base.html" %}

{% block title %}CSV Uploader{% endblock title %}

{% block main-title %}Upload{% endblock main-title %}

{% block content %}
    <form action="#" method="post" enctype="multipart/form-data">
    <div class="form-group">
        {% csrf_token %}
        {{ form }}
    </div>
    <button type="submit" class="btn btn-primary">Upload</button>
    </form>
{% endblock content %}